
# autoload bashcompinit && bashcompinit
alias -g ll="gls --color -la"
alias v="nvim"
alias vim="nvim"
alias gotols="cd ~/sandbox/l-pjxs"
alias gotops="cd ~/sandbox/p-pjxs"
# starship
# export STARSHIP_CONFIG=~/.config/starship/gruvbox.toml
export STARSHIP_CONFIG=~/.config/starship/nord.toml
# export STARSHIP_CONFIG=~/.config/starship/pure.toml
eval "$(starship init zsh)"

# ripgrep/fzf stuff
export FZF_DEFAULT_COMMAND='rg --files --ignore-vcs --hidden'
# export BAT_THEME="Nord"
export BAT_THEME="gruvbox-dark"
# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# rbenv
eval "$(rbenv init - zsh)"

# python debugger stuff
export PYDEVD_DISABLE_FILE_VALIDATION=1

# codelldb
export PATH="$HOME/.local/bin/neovimlldb/extension/adapter:$PATH"

# java stuff
export JAVA_HOME=$(/usr/libexec/java_home -v 22.0.1)
export PATH=$JAVA_HOME/bin:$PATH

# history
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=100000
setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
export HISTORY_IGNORE="(clear|ls|cd|pwd|exit|cd ..)"
alias history='fc -l -100'

# docker (e.g. cli completions)
fpath=(/Users/shaneyost/.docker/completions $fpath)
autoload -Uz compinit
compinit
export PATH=~/repos/cosmos-project:$PATH
